<TabbedLayout>:
    do_default_tab: False
    TabbedPanelItem:
        text: 'Canvas'
        BoxLayout:
            orientation: 'vertical'
            canvas.before:

                StencilPush
                Color:
                    rgba: .7, .7, .7, 1
                Rectangle:
            
                    pos: self.pos
                    size: self.size
                StencilUse
                
                Color:
                    rgba: .7, .7, .7, 1
                Rectangle:
            
                    pos: self.pos
                    size: self.size
            canvas.after:
                StencilUnUse
                Rectangle:
                    pos: self.pos
                    size: self.size
                StencilPop
            
                

            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: .05

                Spinner:
                    #size_hint: .2,.1
                    #pos_hint: {'x': 0.9, 'y': 0.9}
                    text: 'Choose Object'
                    id: objectCreator
                    values: ['Tile Set Template', 'Root Module', 'Module', 'Tile Template', 'Port', 'Initiator Port']
                
                Button:
                    #size_hint: .2,.1
                    #pos_hint: {'x': 0.9, 'y': 0.9}
                    text: "Create Object"
                    on_release: root.createObject()
            
                Button:
                    #size_hint: .2,.1
                    #pos_hint: {'x': 0.9, 'y': 0.9}
                    text: "Delete Object"
                    on_release: root.deleteObject()
            
                Spinner:
                    #size_hint: .2,.1
                    #pos_hint: {'x': 0.9, 'y': 0.9}
                    text: 'Extra Functions'
                    id: functionCreator
                    values: ['Create Join', 'Add Transition', 'Copy Module', 'Rotate Right', 'Rotate Left', 'Create Tiles']
            
                Button:
                    #size_hint: .2,.1
                    #pos_hint: {'x': 0.9, 'y': 0.9}
                    text: "Execute Function"
                    on_release: root.executeFunction()

            ScatterLayout:
                id: scatterID
                size_hint_y: 1

                
                #Label:
                    #id: canvasLabel 
                    #text: "object"
                #DragLabel:
                    #text: "wut wut"
                    #size_hint: (.2, .2)
       
           
               
    TabbedPanelItem:
        text: 'Exit'
        BoxLayout:
            orientation: 'vertical'

            BoxLayout:
                orientation: 'horizontal'

                TextInput:
                    size_hint: .5,.1
                    pos_hint: {'x': 0.5, 'y': 0.1}
                    text: 'Choose File Name'
                    multiline: False



            BoxLayout:
                orientation: 'horizontal'
            
                Button:
                    size_hint: .2,.2
                    pos_hint: {'x': 0.5, 'y': 0.0}
                    text: "Save"
                Button:
                    size_hint: .2,.2
                    pos_hint: {'x': 0.5, 'y': 0.0}
                    text: "Exit Without Saving"

<tile_template>:
    drag_rectangle: self.x - 20 + self.width/2, self.y - 20 + self.height/2, 40, 40 #self.x, self.y, self.width, self.height 
    drag_timeout: 10000000
    drag_distance: 0
    #size: 40,40
    canvas.before:
        Color:
            rgba: .2, .2, .2, 1
        Rectangle:
            pos: self.x - 20 + self.width/2 , self.y - 20 + self.height/2
            size: 40,40 
<module>:
    drag_rectangle: self.x - 100 + self.width/2, self.y - 120 + self.height/2, 200, 240 #self.x, self.y, self.width, self.height 
    drag_timeout: 10000000
    drag_distance: 0
    #size: 40,40
    canvas.before:
        Color:
            rgba: .1, .1, .1, .2
        Ellipse:
            pos: self.x - 100 + self.width/2 , self.y - 120 + self.height/2
            size: 200,240 #self.size
<port>:
    drag_rectangle: self.x - 20 + self.width/2, self.y - 20 + self.height/2, 40, 40 #self.x, self.y, self.width, self.height 
    drag_timeout: 10000000
    drag_distance: 0
    #size: 40,40
    canvas.before:
        Color:
            rgba: .4, .4, .4, 1
        Ellipse:
            pos: self.x - 20 + self.width/2 , self.y - 20 + self.height/2
            size: 40,40 #self.size
<initiator_port>:
    drag_rectangle: self.x - 20 + self.width/2, self.y - 20 + self.height/2, 40, 40 #self.x, self.y, self.width, self.height 
    drag_timeout: 10000000
    drag_distance: 0
    #size: 40,40
    canvas.before:
        Color:
            rgba: .5, .5, .5, 1
        Ellipse:
            pos: self.x - 20 + self.width/2 , self.y - 20 + self.height/2
            size: 40,40 #self.size
 

             
                
                   
        
